import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatDateFull, formatDateShort } from "./date-utils";
import { calculatePercentage } from "./utils";
import { exportAllData } from "./storage";
import type {
  UserProfile,
  PracticeHours,
  CpdRecord,
  FeedbackRecord,
  ReflectiveAccount,
  ReflectiveDiscussion,
  HealthDeclaration,
  Confirmation
} from "@shared/schema";

// Define the base blue color for headers - based on NMC colors
const NMC_BLUE = [0, 84, 164];  // RGB format

/**
 * Generate a download blob for JSON export
 */
export async function generateJsonExport(): Promise<Blob> {
  const data = await exportAllData();
  return new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
}

/**
 * NMC-styled Header with logo placeholder and title
 * Formatted to match the official NMC templates
 */
function addNmcHeader(doc: jsPDF, title: string) {
  // Add NMC-styled header
  doc.setFontSize(16);
  doc.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.setFont('helvetica', 'bold');
  doc.text("Nursing & Midwifery Council", 20, 20);
  
  // Add horizontal line
  doc.setDrawColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.setLineWidth(0.8);
  doc.line(20, 25, 190, 25);
  
  // Add form title (matching NMC template style)
  doc.setFontSize(14);
  doc.text(title, 20, 35);
  
  // Add subtitle commonly seen on NMC forms
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text("For revalidation with the Nursing & Midwifery Council", 20, 42);
  
  // Add small print stating this is not an official NMC document
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text("Revalidation form template matching NMC requirements. Generated by RevalPro.", 20, 48);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
}

/**
 * Add a section header to the PDF
 */
function addSectionHeader(doc: jsPDF, title: string, y: number) {
  doc.setFillColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.rect(20, y, 170, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text(title, 25, y + 5.5);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  return y + 12; // Return next Y position
}

/**
 * Add a field label and value to the PDF
 */
function addField(doc: jsPDF, label: string, value: string, x: number, y: number, width = 80) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(label, x, y);
  doc.setFont('helvetica', 'normal');
  
  // Handle multiline text for value
  const splitValue = doc.splitTextToSize(value || 'Not provided', width);
  doc.text(splitValue, x, y + 5);
  
  // Calculate next Y position based on number of lines
  const lineHeight = 5;
  const lines = splitValue.length;
  return y + (lineHeight * (lines + 1)) + 2;
}

/**
 * Generate the practice hours log PDF
 */
export async function generatePracticeHoursPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const practiceHours = data.practiceHours as PracticeHours[];
  
  addNmcHeader(doc, "Practice hours log");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Practice hours table
  y = addSectionHeader(doc, "Practice hours", y + 5);
  
  // Use autotable plugin
  (doc as any).autoTable({
    startY: y,
    head: [['Work setting', 'Scope of practice', 'Start date', 'End date', 'Hours']],
    body: practiceHours.map(h => [
      h.workSetting,
      h.scope,
      formatDateShort(h.startDate),
      formatDateShort(h.endDate),
      h.hours.toString()
    ]),
    theme: 'grid',
    headStyles: {
      fillColor: [NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]],
      textColor: [255, 255, 255],
      fontSize: 10
    },
    margin: { left: 20, right: 20 },
    tableWidth: 'auto'
  });
  
  y = (doc as any).lastAutoTable.finalY + 15;
  
  // Total hours
  const totalHours = practiceHours.reduce((sum, h) => sum + h.hours, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total practice hours: ${totalHours}`, 20, y);
  
  if (totalHours < 450) {
    doc.setTextColor(220, 0, 0);
    doc.text(`Note: NMC requires a minimum of 450 hours of practice.`, 20, y + 8);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    doc.text(`✓ Meets NMC requirement of 450 hours minimum.`, 20, y + 8);
    doc.setTextColor(0, 0, 0);
  }
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate the CPD records PDF
 */
export async function generateCpdRecordsPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const cpdRecords = data.cpdRecords as CpdRecord[];
  
  addNmcHeader(doc, "Continuing Professional Development (CPD) record");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // CPD summary
  y = addSectionHeader(doc, "CPD summary", y + 5);
  
  const totalHours = cpdRecords.reduce((sum, r) => sum + r.hours, 0);
  const participatoryHours = cpdRecords
    .filter(r => r.participatory)
    .reduce((sum, r) => sum + r.hours, 0);
  
  y = addField(doc, "Total CPD hours:", `${totalHours} hours`, 20, y);
  y = addField(doc, "Participatory learning:", `${participatoryHours} hours`, 20, y);
  
  if (totalHours < 35) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "NMC requirement:", `Minimum 35 hours not met (${totalHours}/35)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "NMC requirement:", `✓ Meets minimum 35 hours (${totalHours}/35)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  if (participatoryHours < 20) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "Participatory requirement:", `Minimum 20 hours not met (${participatoryHours}/20)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "Participatory requirement:", `✓ Meets minimum 20 hours (${participatoryHours}/20)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Detailed CPD records
  // We'll create a new page for each CPD record to ensure they fit properly
  cpdRecords.forEach((record, index) => {
    if (index > 0) doc.addPage();
    
    let pageY = 50;
    pageY = addSectionHeader(doc, `CPD activity ${index + 1}`, pageY);
    
    pageY = addField(doc, "Date completed:", formatDateShort(record.dateCompleted), 20, pageY);
    pageY = addField(doc, "Activity name:", record.name, 20, pageY);
    pageY = addField(doc, "Description:", record.description, 20, pageY, 150);
    pageY = addField(doc, "Hours spent:", `${record.hours} hours`, 20, pageY);
    pageY = addField(doc, "Participatory:", record.participatory ? "Yes" : "No", 20, pageY);
    
    // Method of learning box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Method of learning", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Learning method:", record.method, 20, pageY, 150);
    
    // Reflection box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Reflection on learning", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "What was learned:", record.reflection, 20, pageY, 150);
    pageY = addField(doc, "How has this influenced your practice:", record.impact || "Not provided", 20, pageY, 150);
  });
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate the feedback records PDF
 */
export async function generateFeedbackPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const feedbackRecords = data.feedbackRecords as FeedbackRecord[];
  
  addNmcHeader(doc, "Feedback log");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Feedback summary
  y = addSectionHeader(doc, "Feedback summary", y + 5);
  
  y = addField(doc, "Number of feedback records:", `${feedbackRecords.length}`, 20, y);
  
  if (feedbackRecords.length < 5) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "NMC requirement:", `Minimum 5 records not met (${feedbackRecords.length}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "NMC requirement:", `✓ Meets minimum 5 records (${feedbackRecords.length}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Detailed feedback records
  // We'll create a new page for each feedback record to ensure they fit properly
  feedbackRecords.forEach((record, index) => {
    if (index > 0) doc.addPage();
    
    let pageY = 50;
    pageY = addSectionHeader(doc, `Feedback record ${index + 1}`, pageY);
    
    pageY = addField(doc, "Date received:", formatDateShort(record.dateReceived), 20, pageY);
    pageY = addField(doc, "Source:", record.source, 20, pageY);
    pageY = addField(doc, "Type of feedback:", record.type, 20, pageY);
    
    // Content box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Feedback content", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Content:", record.content, 20, pageY, 150);
    
    // Reflection box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Reflection on feedback", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Reflection:", record.reflection, 20, pageY, 150);
    pageY = addField(doc, "Actions taken as a result:", record.actions, 20, pageY, 150);
  });
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate the reflective accounts PDF
 */
export async function generateReflectiveAccountsPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const reflectiveAccounts = data.reflectiveAccounts as ReflectiveAccount[];
  
  addNmcHeader(doc, "Reflective accounts");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Reflective accounts summary
  y = addSectionHeader(doc, "Reflective accounts summary", y + 5);
  
  y = addField(doc, "Number of reflective accounts:", `${reflectiveAccounts.length}`, 20, y);
  
  if (reflectiveAccounts.length < 5) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "NMC requirement:", `Minimum 5 accounts not met (${reflectiveAccounts.length}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "NMC requirement:", `✓ Meets minimum 5 accounts (${reflectiveAccounts.length}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Detailed reflective accounts
  // We'll create a new page for each reflective account to ensure they fit properly
  reflectiveAccounts.forEach((record, index) => {
    if (index > 0) doc.addPage();
    
    let pageY = 50;
    pageY = addSectionHeader(doc, `Reflective account ${index + 1}`, pageY);
    
    pageY = addField(doc, "Date of experience:", formatDateShort(record.dateOfExperience), 20, pageY);
    pageY = addField(doc, "NMC Code section:", record.codeSection, 20, pageY);
    
    // Experience description box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Experience", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Description of experience:", record.experience, 20, pageY, 150);
    
    // Reflection box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("What did you learn?", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Learning:", record.learning, 20, pageY, 150);
    
    // Changes to practice box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("How has this experience changed your practice?", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Changes to practice:", record.changes, 20, pageY, 150);
  });
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate the reflective discussion form PDF
 */
export async function generateReflectiveDiscussionPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const reflectiveDiscussion = data.reflectiveDiscussion[0] as ReflectiveDiscussion | undefined;
  
  addNmcHeader(doc, "Reflective discussion form");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Discussion Partner Information
  y = addSectionHeader(doc, "Discussion partner", y + 5);
  
  if (reflectiveDiscussion) {
    y = addField(doc, "Name:", reflectiveDiscussion.partnerName || "", 20, y);
    y = addField(doc, "PIN (if applicable):", reflectiveDiscussion.partnerPin || "", 20, y);
    y = addField(doc, "Email:", reflectiveDiscussion.partnerEmail || "", 20, y);
    y = addField(doc, "Professional address:", reflectiveDiscussion.partnerAddress || "", 20, y, 150);
    y = addField(doc, "Date of discussion:", formatDateShort(reflectiveDiscussion.discussionDate), 20, y);
    
    // Discussion content box
    y = addSectionHeader(doc, "Discussion content", y + 5);
    y = addField(doc, "Notes:", reflectiveDiscussion.notes || "", 20, y, 150);
    
    // Declaration box
    y = addSectionHeader(doc, "Declaration", y + 5);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text([
      "I confirm that I have discussed five written reflective accounts with the named nurse,",
      "midwife or nursing associate as part of a professional discussion about their practice,",
      "and their professional development."
    ], 20, y);
    
    y += 15;
    
    if (reflectiveDiscussion.completed) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 130, 0);
      doc.text("✓ Discussion completed and confirmed", 20, y);
      doc.setTextColor(0, 0, 0);
    } else {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(220, 0, 0);
      doc.text("✗ Discussion not yet completed", 20, y);
      doc.setTextColor(0, 0, 0);
    }
  } else {
    y = addField(doc, "Status:", "Reflective discussion not yet recorded", 20, y);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Reflective discussion not yet completed", 20, y + 10);
    doc.setTextColor(0, 0, 0);
  }
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate the health and character declaration PDF
 */
export async function generateHealthDeclarationPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const healthDeclaration = data.healthDeclaration[0] as HealthDeclaration | undefined;
  
  addNmcHeader(doc, "Health and character declaration");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Health declaration
  y = addSectionHeader(doc, "Health declaration", y + 5);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text([
    "I declare that my health and character are sufficiently good to enable me to practice safely",
    "and effectively, and meet the requirements of the NMC's The Code."
  ], 20, y);
  
  y += 15;
  
  if (healthDeclaration?.healthDeclaration) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 130, 0);
    doc.text("✓ Health declaration confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Health declaration not yet confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  y += 15;
  
  // Character declaration
  y = addSectionHeader(doc, "Character declaration", y);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text([
    "I declare that:",
    "• I have not been convicted of any criminal offence or issued with a formal caution;",
    "• I am not currently the subject of any police investigation or any investigation by any",
    "  regulatory or healthcare body in the UK or elsewhere;",
    "• I have not had any judgment against me in a civil case related to my practice;",
    "• I have not been the subject of any adverse determination by any regulatory body in the UK",
    "  or elsewhere that my fitness to practise is impaired;"
  ], 20, y);
  
  y += 40;
  
  if (healthDeclaration?.characterDeclaration) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 130, 0);
    doc.text("✓ Character declaration confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Character declaration not yet confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  y += 15;
  
  // Declaration confirmation
  if (healthDeclaration?.completed) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 130, 0);
    doc.text("✓ Overall health and character declarations completed", 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Overall health and character declarations not yet completed", 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate the confirmation form PDF
 */
export async function generateConfirmationPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const confirmation = data.confirmation[0] as Confirmation | undefined;
  
  addNmcHeader(doc, "Confirmation form");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Confirmer Information
  y = addSectionHeader(doc, "Confirmer details", y + 5);
  
  if (confirmation) {
    y = addField(doc, "Name:", confirmation.confirmerName || "", 20, y);
    y = addField(doc, "PIN (if applicable):", confirmation.confirmerPin || "", 20, y);
    y = addField(doc, "Email:", confirmation.confirmerEmail || "", 20, y);
    y = addField(doc, "Professional address:", confirmation.confirmerAddress || "", 20, y, 150);
    y = addField(doc, "Date of confirmation:", formatDateShort(confirmation.confirmationDate), 20, y);
    y = addField(doc, "Relationship to nurse:", confirmation.relationship || "", 20, y);
    
    // Confirmation declaration box
    y = addSectionHeader(doc, "Confirmation declaration", y + 5);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text([
      "I confirm that I have discussed the revalidation requirements with the nurse named above,",
      "and that the nurse has demonstrated to me that they have complied with all of the NMC",
      "revalidation requirements listed below over the three years since their last renewal or",
      "since joining the register as set out in How to revalidate with the NMC:",
      "",
      "• 450 practice hours or 900 practice hours if renewing as both a nurse and midwife",
      "• 35 hours Continuing Professional Development (of which 20 must be participatory)",
      "• Five pieces of practice-related feedback",
      "• Five written reflective accounts",
      "• Reflective discussion",
      "• Health and character declaration",
      "• Professional indemnity arrangement"
    ], 20, y);
    
    y += 90;
    
    if (confirmation.completed) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 130, 0);
      doc.text("✓ Confirmation completed", 20, y);
      doc.setTextColor(0, 0, 0);
    } else {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(220, 0, 0);
      doc.text("✗ Confirmation not yet completed", 20, y);
      doc.setTextColor(0, 0, 0);
    }
  } else {
    y = addField(doc, "Status:", "Confirmation not yet recorded", 20, y);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Confirmation not yet completed", 20, y + 10);
    doc.setTextColor(0, 0, 0);
  }
  
  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

/**
 * Generate and download complete revalidation pack as PDF
 */
export async function downloadRevalidationPack(): Promise<void> {
  try {
    // Create all individual documents
    const practiceHoursPdf = await generatePracticeHoursPdf();
    const cpdPdf = await generateCpdRecordsPdf();
    const feedbackPdf = await generateFeedbackPdf();
    const reflectiveAccountsPdf = await generateReflectiveAccountsPdf();
    const reflectiveDiscussionPdf = await generateReflectiveDiscussionPdf();
    const healthDeclarationPdf = await generateHealthDeclarationPdf();
    const confirmationPdf = await generateConfirmationPdf();
    
    // Create a new PDF to combine all documents
    const combinedPdf = new jsPDF();
    let currentPage = 0;
    
    // Helper function to add pages from one PDF to another
    const addPagesToDocument = (sourcePdf: jsPDF) => {
      const pageCount = sourcePdf.getNumberOfPages();
      
      for (let i = 1; i <= pageCount; i++) {
        if (currentPage > 0) {
          combinedPdf.addPage();
        }
        
        // Get the page content from the source PDF
        const pageContent = sourcePdf.output('arraybuffer');
        
        // Add the page to the combined PDF
        combinedPdf.addPage();
        combinedPdf.setPage(currentPage + 1);
        combinedPdf.addImage(pageContent, 'JPEG', 0, 0, 210, 297, '', 'FAST');
        
        currentPage++;
      }
    };
    
    // Add cover page
    const data = await exportAllData();
    const userProfile = data.userProfile[0] as UserProfile | undefined;
    
    combinedPdf.setFontSize(24);
    combinedPdf.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
    combinedPdf.text("RevalPro", 105, 40, { align: 'center' });
    
    combinedPdf.setFontSize(20);
    combinedPdf.text("Complete Revalidation Documentation", 105, 60, { align: 'center' });
    
    combinedPdf.setFontSize(14);
    combinedPdf.setTextColor(0, 0, 0);
    combinedPdf.text(`Prepared for: ${userProfile?.name || ""}`, 105, 80, { align: 'center' });
    combinedPdf.text(`NMC PIN: ${userProfile?.registrationNumber || ""}`, 105, 90, { align: 'center' });
    combinedPdf.text(`Revalidation due: ${userProfile?.expiryDate ? formatDateFull(userProfile.expiryDate) : ""}`, 105, 100, { align: 'center' });
    
    combinedPdf.setFontSize(12);
    combinedPdf.text("This pack contains all documentation required for NMC revalidation:", 105, 130, { align: 'center' });
    
    const contentList = [
      "• Practice hours log",
      "• CPD records",
      "• Feedback log",
      "• Reflective accounts",
      "• Reflective discussion form",
      "• Health and character declaration",
      "• Confirmation form"
    ];
    
    combinedPdf.setFontSize(11);
    contentList.forEach((item, index) => {
      combinedPdf.text(item, 105, 150 + (index * 10), { align: 'center' });
    });
    
    combinedPdf.setFontSize(10);
    combinedPdf.text(`Generated on: ${formatDateFull(new Date())}`, 105, 240, { align: 'center' });
    combinedPdf.text("RevalPro - Nursing Revalidation Assistance App", 105, 250, { align: 'center' });
    
    currentPage = 1;
    
    // Add all documents
    addPagesToDocument(practiceHoursPdf);
    addPagesToDocument(cpdPdf);
    addPagesToDocument(feedbackPdf);
    addPagesToDocument(reflectiveAccountsPdf);
    addPagesToDocument(reflectiveDiscussionPdf);
    addPagesToDocument(healthDeclarationPdf);
    addPagesToDocument(confirmationPdf);
    
    // Generate and download the combined PDF
    const pdfOutput = combinedPdf.output('blob');
    const url = URL.createObjectURL(pdfOutput);
    const a = document.createElement("a");
    a.href = url;
    a.download = `complete-revalidation-pack-${formatDateShort(new Date()).replace(/\//g, '-')}.pdf`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error("Error generating PDF pack:", error);
    throw new Error("Failed to generate revalidation pack");
  }
}

/**
 * Generate and download a specific form as PDF
 */
export async function downloadSpecificForm(formType: string): Promise<void> {
  try {
    let pdf: jsPDF;
    let filename: string;
    
    switch (formType) {
      case 'practiceHours':
        pdf = await generatePracticeHoursPdf();
        filename = 'practice-hours-log';
        break;
      case 'cpd':
        pdf = await generateCpdRecordsPdf();
        filename = 'cpd-records';
        break;
      case 'feedback':
        pdf = await generateFeedbackPdf();
        filename = 'feedback-log';
        break;
      case 'reflectiveAccounts':
        pdf = await generateReflectiveAccountsPdf();
        filename = 'reflective-accounts';
        break;
      case 'reflectiveDiscussion':
        pdf = await generateReflectiveDiscussionPdf();
        filename = 'reflective-discussion-form';
        break;
      case 'healthDeclaration':
        pdf = await generateHealthDeclarationPdf();
        filename = 'health-character-declaration';
        break;
      case 'confirmation':
        pdf = await generateConfirmationPdf();
        filename = 'confirmation-form';
        break;
      default:
        throw new Error(`Unknown form type: ${formType}`);
    }
    
    // Generate and download the PDF
    const pdfOutput = pdf.output('blob');
    const url = URL.createObjectURL(pdfOutput);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename}-${formatDateShort(new Date()).replace(/\//g, '-')}.pdf`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error(`Error generating ${formType} PDF:`, error);
    throw new Error(`Failed to generate ${formType} form`);
  }
}

/**
 * Generate and download a summary report PDF
 * This creates a concise summary of all revalidation data
 */
export async function downloadSummaryReport(): Promise<void> {
  try {
    const doc = new jsPDF();
    const data = await exportAllData();
    
    const userProfile = data.userProfile[0] as UserProfile | undefined;
    const practiceHours = data.practiceHours as PracticeHours[];
    const cpdRecords = data.cpdRecords as CpdRecord[];
    const feedbackRecords = data.feedbackRecords as FeedbackRecord[];
    const reflectiveAccounts = data.reflectiveAccounts as ReflectiveAccount[];
    const reflectiveDiscussion = data.reflectiveDiscussion[0] as ReflectiveDiscussion | undefined;
    const healthDeclaration = data.healthDeclaration[0] as HealthDeclaration | undefined;
    const confirmation = data.confirmation[0] as Confirmation | undefined;
    
    // Calculate completion metrics
    const practiceHoursTotal = practiceHours.reduce((sum, h) => sum + h.hours, 0);
    const cpdTotal = cpdRecords.reduce((sum, r) => sum + r.hours, 0);
    const cpdParticipatory = cpdRecords
      .filter(r => r.participatory)
      .reduce((sum, r) => sum + r.hours, 0);
    
    // Calculate completion percentages
    const practiceHoursPercentage = calculatePercentage(practiceHoursTotal, 450);
    const cpdPercentage = calculatePercentage(cpdTotal, 35);
    const participatoryPercentage = calculatePercentage(cpdParticipatory, 20);
    const feedbackPercentage = calculatePercentage(feedbackRecords.length, 5);
    const reflectionPercentage = calculatePercentage(reflectiveAccounts.length, 5);
    const reflectiveDiscussionCompleted = reflectiveDiscussion?.completed ? 100 : 0;
    const healthDeclarationCompleted = healthDeclaration?.completed ? 100 : 0;
    const confirmationCompleted = confirmation?.completed ? 100 : 0;
    
    // Calculate overall percentage
    const totalRequirements = 7; // Total number of requirements
    const overallPercentage = Math.round(
      (
        practiceHoursPercentage + 
        cpdPercentage + 
        feedbackPercentage + 
        reflectionPercentage + 
        reflectiveDiscussionCompleted + 
        healthDeclarationCompleted + 
        confirmationCompleted
      ) / totalRequirements
    );
    
    addNmcHeader(doc, "Revalidation Summary Report");
    
    let y = 50;
    
    // Nurse Information
    y = addSectionHeader(doc, "Your details", y);
    y = addField(doc, "Name:", userProfile?.name || "", 20, y);
    y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
    y = addField(doc, "Revalidation due:", userProfile?.expiryDate ? formatDateFull(userProfile.expiryDate) : "", 20, y);
    
    // Overall completion
    y = addSectionHeader(doc, "Overall completion status", y + 5);
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    
    if (overallPercentage < 100) {
      doc.setTextColor(220, 0, 0);
      doc.text(`Overall completion: ${overallPercentage}% - NOT YET COMPLETE`, 20, y);
    } else {
      doc.setTextColor(0, 130, 0);
      doc.text(`Overall completion: ${overallPercentage}% - FULLY COMPLETE ✓`, 20, y);
    }
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    y += 10;
    
    // Summary table using autoTable
    (doc as any).autoTable({
      startY: y,
      head: [['Requirement', 'Target', 'Current status', 'Complete?']],
      body: [
        [
          'Practice hours', 
          '450 hours', 
          `${practiceHoursTotal} hours`, 
          practiceHoursTotal >= 450 ? '✓' : '✗'
        ],
        [
          'CPD hours (total)', 
          '35 hours', 
          `${cpdTotal} hours`, 
          cpdTotal >= 35 ? '✓' : '✗'
        ],
        [
          'CPD hours (participatory)', 
          '20 hours', 
          `${cpdParticipatory} hours`, 
          cpdParticipatory >= 20 ? '✓' : '✗'
        ],
        [
          'Feedback records', 
          '5 records', 
          `${feedbackRecords.length} records`, 
          feedbackRecords.length >= 5 ? '✓' : '✗'
        ],
        [
          'Reflective accounts', 
          '5 accounts', 
          `${reflectiveAccounts.length} accounts`, 
          reflectiveAccounts.length >= 5 ? '✓' : '✗'
        ],
        [
          'Reflective discussion', 
          'Completed', 
          reflectiveDiscussion?.completed ? 'Completed' : 'Not completed', 
          reflectiveDiscussion?.completed ? '✓' : '✗'
        ],
        [
          'Health & character', 
          'Completed', 
          healthDeclaration?.completed ? 'Completed' : 'Not completed', 
          healthDeclaration?.completed ? '✓' : '✗'
        ],
        [
          'Confirmation', 
          'Completed', 
          confirmation?.completed ? 'Completed' : 'Not completed', 
          confirmation?.completed ? '✓' : '✗'
        ]
      ],
      theme: 'grid',
      headStyles: {
        fillColor: [NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]],
        textColor: [255, 255, 255],
        fontSize: 10
      },
      columnStyles: {
        3: { 
          halign: 'center',
          fontStyle: 'bold'
        }
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240]
      },
      margin: { left: 20, right: 20 }
    });
    
    y = (doc as any).lastAutoTable.finalY + 15;
    
    // Next steps / remaining tasks
    if (overallPercentage < 100) {
      y = addSectionHeader(doc, "Remaining tasks", y);
      
      const remainingTasks = [];
      
      if (practiceHoursTotal < 450) {
        remainingTasks.push(`• Record additional practice hours (${450 - practiceHoursTotal} more hours needed)`);
      }
      
      if (cpdTotal < 35) {
        remainingTasks.push(`• Complete more CPD activities (${35 - cpdTotal} more hours needed)`);
      }
      
      if (cpdParticipatory < 20) {
        remainingTasks.push(`• Complete more participatory CPD (${20 - cpdParticipatory} more hours needed)`);
      }
      
      if (feedbackRecords.length < 5) {
        remainingTasks.push(`• Record more feedback (${5 - feedbackRecords.length} more records needed)`);
      }
      
      if (reflectiveAccounts.length < 5) {
        remainingTasks.push(`• Write more reflective accounts (${5 - reflectiveAccounts.length} more accounts needed)`);
      }
      
      if (!reflectiveDiscussion?.completed) {
        remainingTasks.push(`• Complete reflective discussion`);
      }
      
      if (!healthDeclaration?.completed) {
        remainingTasks.push(`• Complete health and character declaration`);
      }
      
      if (!confirmation?.completed) {
        remainingTasks.push(`• Obtain confirmation`);
      }
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      remainingTasks.forEach((task, index) => {
        doc.text(task, 20, y + (index * 7));
      });
    } else {
      y = addSectionHeader(doc, "Ready to submit", y);
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 130, 0);
      doc.text("✓ All revalidation requirements have been met", 20, y + 7);
      doc.text("You are ready to submit your application to the NMC", 20, y + 17);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.text([
        "Remember to submit your application via the NMC website:",
        "https://www.nmc.org.uk/revalidation/",
        "",
        "You can download the complete pack of required documentation from the app"
      ], 20, y + 30);
    }
    
    // Add footer with page numbers
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(
        `Page ${i} of ${totalPages} - Generated by RevalPro on ${formatDateFull(new Date())}`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }
    
    // Generate and download the PDF
    const pdfOutput = doc.output('blob');
    const url = URL.createObjectURL(pdfOutput);
    const a = document.createElement("a");
    a.href = url;
    a.download = `revalidation-summary-${formatDateShort(new Date()).replace(/\//g, '-')}.pdf`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error("Error generating summary report:", error);
    throw new Error("Failed to generate summary report");
  }
}

/**
 * Generate and download raw data as JSON 
 */
export async function downloadRawData(): Promise<void> {
  try {
    const blob = await generateJsonExport();
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `revalidation-data-${formatDateShort(new Date()).replace(/\//g, '-')}.json`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error("Error exporting data:", error);
    throw new Error("Failed to export revalidation data");
  }
}
