import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatDateFull, formatDateShort } from "./date-utils";
import { calculatePercentage } from "./utils";
import { exportAllData } from "./storage";
import type {
  UserProfile,
  PracticeHours,
  CpdRecord,
  FeedbackRecord,
  ReflectiveAccount,
  ReflectiveDiscussion,
  HealthDeclaration,
  Confirmation
} from "@shared/schema";

// Define the base blue color for headers - based on NMC colors
const NMC_BLUE = [0, 84, 164];  // RGB format

/**
 * Generate a download blob for JSON export
 */
export async function generateJsonExport(): Promise<Blob> {
  const data = await exportAllData();
  return new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
}

/**
 * NMC-styled Header with logo placeholder and title
 * Formatted to match the official NMC templates
 */
function addNmcHeader(doc: jsPDF, title: string) {
  // Add NMC-styled header
  doc.setFontSize(16);
  doc.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.setFont('helvetica', 'bold');
  doc.text("Nursing & Midwifery Council", 20, 20);
  
  // Add horizontal line
  doc.setDrawColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.setLineWidth(0.8);
  doc.line(20, 25, 190, 25);
  
  // Add form title (matching NMC template style)
  doc.setFontSize(14);
  doc.text(title, 20, 35);
  
  // Add subtitle commonly seen on NMC forms
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text("For revalidation with the Nursing & Midwifery Council", 20, 42);
  
  // Add small print stating this is not an official NMC document
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text("Revalidation form template matching NMC requirements. Generated by RevalPro.", 20, 48);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
}

/**
 * Add a section header to the PDF
 * Follows NMC template style with grey background and blue text
 */
function addSectionHeader(doc: jsPDF, title: string, y: number) {
  // Use light grey background for section headers (NMC style)
  doc.setFillColor(240, 240, 240);
  doc.rect(20, y, 170, 10, 'F');
  
  // Use NMC blue text for the header
  doc.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 25, y + 6.5);
  
  // Reset text format
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  return y + 14; // Return next Y position with more spacing
}

/**
 * Add NMC-styled footer with page numbers to all pages
 */
function addNmcFooter(doc: jsPDF) {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // Add horizontal line at bottom of page (NMC style)
    doc.setDrawColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
    doc.setLineWidth(0.5);
    doc.line(20, doc.internal.pageSize.getHeight() - 20, 
             doc.internal.pageSize.getWidth() - 20, 
             doc.internal.pageSize.getHeight() - 20);
    
    // Add page numbers in NMC format
    doc.setFontSize(8);
    doc.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
    doc.text(
      `Page ${i} of ${totalPages}`,
      20,
      doc.internal.pageSize.getHeight() - 12
    );
    
    // Add date on right side (NMC style)
    doc.text(
      `Generated: ${formatDateFull(new Date())}`,
      doc.internal.pageSize.getWidth() - 20,
      doc.internal.pageSize.getHeight() - 12,
      { align: 'right' }
    );
    
    // Reset text color
    doc.setTextColor(0, 0, 0);
  }
}

/**
 * Add a field label and value to the PDF
 * Follows NMC form format with proper field styling
 */
function addField(doc: jsPDF, label: string, value: string, x: number, y: number, width = 80) {
  // Use NMC blue for field labels
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
  doc.text(label, x, y);
  
  // Add light grey box for value (common in NMC forms)
  const valueY = y + 3;
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(252, 252, 252);
  
  // Handle multiline text for value
  const splitValue = doc.splitTextToSize(value || 'Not provided', width);
  const lines = splitValue.length;
  const boxHeight = lines * 5 + 6;
  
  // Draw box for value with rounded corners
  doc.roundedRect(x, valueY, width + 5, boxHeight, 1, 1, 'FD');
  
  // Add value text
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(splitValue, x + 3, valueY + 5);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Calculate next Y position based on number of lines
  return y + boxHeight + 8;
}

// --- RENDERING HELPERS ---

async function renderPracticeHoursToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const practiceHours = data.practiceHours as PracticeHours[];
  
  addNmcHeader(doc, "Practice hours log");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Practice hours table
  y = addSectionHeader(doc, "Practice hours", y + 5);
  
  // Use autotable plugin
  (doc as any).autoTable({
    startY: y,
    head: [['Work setting', 'Scope of practice', 'Start date', 'End date', 'Hours']],
    body: practiceHours.map(h => [
      h.workSetting,
      h.scope,
      formatDateShort(h.startDate),
      formatDateShort(h.endDate),
      h.hours.toString()
    ]),
    theme: 'grid',
    headStyles: {
      fillColor: [NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]],
      textColor: [255, 255, 255],
      fontSize: 10
    },
    margin: { left: 20, right: 20 },
    tableWidth: 'auto'
  });
  
  y = (doc as any).lastAutoTable.finalY + 15;
  
  // Total hours
  const totalHours = practiceHours.reduce((sum: number, h: PracticeHours) => sum + h.hours, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total practice hours: ${totalHours}`, 20, y);
  
  if (totalHours < 450) {
    doc.setTextColor(220, 0, 0);
    doc.text(`Note: NMC requires a minimum of 450 hours of practice.`, 20, y + 8);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    doc.text(`✓ Meets NMC requirement of 450 hours minimum.`, 20, y + 8);
    doc.setTextColor(0, 0, 0);
  }
}

async function renderCpdRecordsToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const cpdRecords = data.cpdRecords as CpdRecord[];
  
  addNmcHeader(doc, "Continuing Professional Development (CPD) record");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // CPD summary
  y = addSectionHeader(doc, "CPD summary", y + 5);
  
  const totalHours = cpdRecords.reduce((sum: number, r: CpdRecord) => sum + r.hours, 0);
  const participatoryHours = cpdRecords
    .filter((r: CpdRecord) => r.participatory)
    .reduce((sum: number, r: CpdRecord) => sum + r.hours, 0);
  
  y = addField(doc, "Total CPD hours:", `${totalHours} hours`, 20, y);
  y = addField(doc, "Participatory learning:", `${participatoryHours} hours`, 20, y);
  
  if (totalHours < 35) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "NMC requirement:", `Minimum 35 hours not met (${totalHours}/35)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "NMC requirement:", `✓ Meets minimum 35 hours (${totalHours}/35)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  if (participatoryHours < 20) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "Participatory requirement:", `Minimum 20 hours not met (${participatoryHours}/20)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "Participatory requirement:", `✓ Meets minimum 20 hours (${participatoryHours}/20)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Detailed CPD records
  cpdRecords.forEach((record, index) => {
    doc.addPage();
    addNmcHeader(doc, "Continuing Professional Development (CPD) record");
    
    let pageY = 50;
    pageY = addSectionHeader(doc, `CPD activity ${index + 1}`, pageY);
    
    pageY = addField(doc, "Date completed:", formatDateShort(record.date), 20, pageY);
    pageY = addField(doc, "Activity name:", record.title, 20, pageY);
    pageY = addField(doc, "Description:", record.description || "", 20, pageY, 150);
    pageY = addField(doc, "Hours spent:", `${record.hours} hours`, 20, pageY);
    pageY = addField(doc, "Participatory:", record.participatory ? "Yes" : "No", 20, pageY);
    
    // Method of learning box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, pageY, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Relevance to Code", 25, pageY + 5.5);
    pageY += 12;
    
    pageY = addField(doc, "Relevance:", record.relevanceToCode || "", 20, pageY, 150);
  });
}

async function renderFeedbackToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const feedbackRecords = data.feedbackRecords as FeedbackRecord[];
  
  addNmcHeader(doc, "Practice-related feedback log");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Feedback summary
  y = addSectionHeader(doc, "Feedback summary", y + 5);
  
  const totalFeedback = feedbackRecords.length;
  
  if (totalFeedback < 5) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "NMC requirement:", `Minimum 5 pieces not met (${totalFeedback}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "NMC requirement:", `✓ Meets minimum 5 pieces (${totalFeedback}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Detailed Feedback records
  feedbackRecords.forEach((record, index) => {
    doc.addPage();
    addNmcHeader(doc, "Practice-related feedback log");
    
    let pageY = 50;
    pageY = addSectionHeader(doc, `Feedback ${index + 1}`, pageY);
    
    pageY = addField(doc, "Date received:", formatDateShort(record.date), 20, pageY);
    pageY = addField(doc, "Source of feedback:", record.source, 20, pageY);
    pageY = addField(doc, "Content of feedback:", record.content, 20, pageY, 150);
    pageY = addField(doc, "How this influenced your practice:", record.reflection || "", 20, pageY, 150);
  });
}

async function renderReflectiveAccountsToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const reflectiveAccounts = data.reflectiveAccounts as ReflectiveAccount[];
  
  addNmcHeader(doc, "Reflective accounts form");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Accounts summary
  y = addSectionHeader(doc, "Reflective accounts summary", y + 5);
  
  const totalAccounts = reflectiveAccounts.length;
  
  if (totalAccounts < 5) {
    doc.setTextColor(220, 0, 0);
    y = addField(doc, "NMC requirement:", `Minimum 5 accounts not met (${totalAccounts}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(0, 130, 0);
    y = addField(doc, "NMC requirement:", `✓ Meets minimum 5 accounts (${totalAccounts}/5)`, 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  // Detailed Reflective Accounts
  reflectiveAccounts.forEach((account, index) => {
    doc.addPage();
    addNmcHeader(doc, "Reflective accounts form");
    
    let pageY = 50;
    pageY = addSectionHeader(doc, `Reflective account ${index + 1}`, pageY);
    
    pageY = addField(doc, "Date:", formatDateShort(account.date), 20, pageY);
    pageY = addField(doc, "Title:", account.title, 20, pageY);
    
    pageY = addSectionHeader(doc, "What was the nature of the CPD activity and/or practice-related feedback and/or event or experience in your practice?", pageY + 5);
    pageY = addField(doc, "Response:", account.experience, 20, pageY, 150);
    
    pageY = addSectionHeader(doc, "What did you learn from the CPD activity and/or feedback and/or event or experience in your practice?", pageY + 5);
    pageY = addField(doc, "Response:", account.whatLearned, 20, pageY, 150);
    
    pageY = addSectionHeader(doc, "How did you change or improve your practice as a result?", pageY + 5);
    pageY = addField(doc, "Response:", account.howChanged, 20, pageY, 150);
    
    pageY = addSectionHeader(doc, "How is this relevant to the Code?", pageY + 5);
    pageY = addField(doc, "Response:", account.codeRelation, 20, pageY, 150);
  });
}

async function renderReflectiveDiscussionToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const reflectiveDiscussion = data.reflectiveDiscussion[0] as ReflectiveDiscussion | undefined;
  
  addNmcHeader(doc, "Reflective discussion form");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Discussion Partner Information
  y = addSectionHeader(doc, "Discussion partner", y + 5);
  
  if (reflectiveDiscussion) {
    y = addField(doc, "Name:", reflectiveDiscussion.partnerName || "", 20, y);
    y = addField(doc, "PIN (if applicable):", reflectiveDiscussion.partnerNmcPin || "", 20, y);
    y = addField(doc, "Email:", reflectiveDiscussion.email || "", 20, y);
    y = addField(doc, "Date of discussion:", formatDateShort(reflectiveDiscussion.date), 20, y);
    
    // Discussion content box
    y = addSectionHeader(doc, "Discussion content", y + 5);
    y = addField(doc, "Notes:", reflectiveDiscussion.notes || "", 20, y, 150);
    
    // Declaration box
    y = addSectionHeader(doc, "Declaration", y + 5);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text([
      "I confirm that I have discussed five written reflective accounts with the named nurse,",
      "midwife or nursing associate as part of a professional discussion about their practice,",
      "and their professional development."
    ], 20, y);
    
    y += 15;
    
    if (reflectiveDiscussion.completed) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 130, 0);
      doc.text("✓ Discussion completed and confirmed", 20, y);
      doc.setTextColor(0, 0, 0);
    } else {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(220, 0, 0);
      doc.text("✗ Discussion not yet completed", 20, y);
      doc.setTextColor(0, 0, 0);
    }
  } else {
    y = addField(doc, "Status:", "Reflective discussion not yet recorded", 20, y);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Reflective discussion not yet completed", 20, y + 10);
    doc.setTextColor(0, 0, 0);
  }
}

async function renderHealthDeclarationToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const healthDeclaration = data.healthDeclaration[0] as HealthDeclaration | undefined;
  
  addNmcHeader(doc, "Health and character declaration");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Health declaration
  y = addSectionHeader(doc, "Health declaration", y + 5);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text([
    "I declare that my health and character are sufficiently good to enable me to practice safely",
    "and effectively, and meet the requirements of the NMC's The Code."
  ], 20, y);
  
  y += 15;
  
  if (healthDeclaration?.goodHealth) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 130, 0);
    doc.text("✓ Health declaration confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Health declaration not yet confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  y += 15;
  
  // Character declaration
  y = addSectionHeader(doc, "Character declaration", y);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text([
    "I declare that:",
    "• I have not been convicted of any criminal offence or issued with a formal caution;",
    "• I am not currently the subject of any police investigation or any investigation by any",
    "  regulatory or healthcare body in the UK or elsewhere;",
    "• I have not had any judgment against me in a civil case related to my practice;",
    "• I have not been the subject of any adverse determination by any regulatory body in the UK",
    "  or elsewhere that my fitness to practise is impaired;"
  ], 20, y);
  
  y += 40;
  
  if (healthDeclaration?.goodCharacter) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 130, 0);
    doc.text("✓ Character declaration confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Character declaration not yet confirmed", 20, y);
    doc.setTextColor(0, 0, 0);
  }
  
  y += 15;
  
  // Declaration confirmation
  if (healthDeclaration?.completed) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 130, 0);
    doc.text("✓ Overall health and character declarations completed", 20, y);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Overall health and character declarations not yet completed", 20, y);
    doc.setTextColor(0, 0, 0);
  }
}

async function renderConfirmationToDoc(doc: jsPDF, data: any) {
  const userProfile = data.userProfile[0] as UserProfile | undefined;
  const confirmation = data.confirmation[0] as Confirmation | undefined;
  
  addNmcHeader(doc, "Confirmation form");
  
  let y = 50;
  
  // Nurse Information
  y = addSectionHeader(doc, "Your details", y);
  y = addField(doc, "Name:", userProfile?.name || "", 20, y);
  y = addField(doc, "NMC PIN:", userProfile?.registrationNumber || "", 20, y);
  
  // Confirmer Information
  y = addSectionHeader(doc, "Confirmer details", y + 5);
  
  if (confirmation) {
    y = addField(doc, "Name:", confirmation.confirmerName || "", 20, y);
    y = addField(doc, "PIN (if applicable):", confirmation.confirmerNmcPin || "", 20, y);
    y = addField(doc, "Email:", confirmation.confirmerEmail || "", 20, y);
    y = addField(doc, "Relationship:", confirmation.confirmerRelationship || "", 20, y);
    y = addField(doc, "Date of confirmation:", formatDateShort(confirmation.confirmationDate), 20, y);
    
    // Confirmation declaration box
    y = addSectionHeader(doc, "Confirmation declaration", y + 5);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text([
      "I confirm that I have discussed the revalidation requirements with the nurse, midwife or nursing",
      "associate named above, and that the nurse, midwife or nursing associate has demonstrated to me",
      "that they have complied with all of the NMC revalidation requirements listed below over the three",
      "years since their last renewal or since joining the register as set out in How to revalidate with the NMC:",
      "",
      "• 450 practice hours or 900 practice hours if renewing as both a nurse and midwife",
      "• 35 hours Continuing Professional Development (of which 20 must be participatory)",
      "• Five pieces of practice-related feedback",
      "• Five written reflective accounts",
      "• Reflective discussion",
      "• Health and character declaration",
      "• Professional indemnity arrangement"
    ], 20, y);
    
    y += 90;
    
    if (confirmation.completed) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 130, 0);
      doc.text("✓ Confirmation completed", 20, y);
      doc.setTextColor(0, 0, 0);
    } else {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(220, 0, 0);
      doc.text("✗ Confirmation not yet completed", 20, y);
      doc.setTextColor(0, 0, 0);
    }
  } else {
    y = addField(doc, "Status:", "Confirmation not yet recorded", 20, y);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 0, 0);
    doc.text("✗ Confirmation not yet completed", 20, y + 10);
    doc.setTextColor(0, 0, 0);
  }
}

// --- PUBLIC EXPORT FUNCTIONS ---

export async function generatePracticeHoursPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderPracticeHoursToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

export async function generateCpdRecordsPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderCpdRecordsToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

export async function generateFeedbackPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderFeedbackToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

export async function generateReflectiveAccountsPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderReflectiveAccountsToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

export async function generateReflectiveDiscussionPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderReflectiveDiscussionToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

export async function generateHealthDeclarationPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderHealthDeclarationToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

export async function generateConfirmationPdf(): Promise<jsPDF> {
  const doc = new jsPDF();
  const data = await exportAllData();
  await renderConfirmationToDoc(doc, data);
  addNmcFooter(doc);
  return doc;
}

/**
 * Generate and download complete revalidation pack as PDF
 */
export async function downloadRevalidationPack(): Promise<void> {
  try {
    // Show user feedback that the process is starting
    const toast = document.createElement('div');
    toast.className = 'fixed bottom-4 right-4 bg-revalpro-blue text-white px-4 py-2 rounded shadow-lg z-50';
    toast.textContent = 'Generating NMC-format documents...';
    document.body.appendChild(toast);
    
    // Create a single PDF document for the complete pack
    const doc = new jsPDF();
    const data = await exportAllData();
    const userProfile = data.userProfile[0] as UserProfile | undefined;
    
    // --- COVER PAGE ---
    
    // NMC header
    doc.setFontSize(24);
    doc.setTextColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
    doc.setFont('helvetica', 'bold');
    doc.text("Nursing & Midwifery Council", 105, 40, { align: 'center' });
    
    // Horizontal line
    doc.setDrawColor(NMC_BLUE[0], NMC_BLUE[1], NMC_BLUE[2]);
    doc.setLineWidth(1);
    doc.line(50, 50, 160, 50);
    
    // Title
    doc.setFontSize(22);
    doc.text("Complete Revalidation Documentation", 105, 60, { align: 'center' });
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Prepared for: ${userProfile?.name || ""}`, 105, 80, { align: 'center' });
    doc.text(`NMC PIN: ${userProfile?.registrationNumber || ""}`, 105, 90, { align: 'center' });
    doc.text(`Revalidation due: ${userProfile?.expiryDate ? formatDateFull(userProfile.expiryDate) : ""}`, 105, 100, { align: 'center' });
    
    doc.setFontSize(12);
    doc.text("This pack contains all documentation required for NMC revalidation:", 105, 130, { align: 'center' });
    
    const contentList = [
      "• Practice hours log",
      "• CPD records",
      "• Feedback log",
      "• Reflective accounts",
      "• Reflective discussion form",
      "• Health and character declaration",
      "• Confirmation form"
    ];
    
    doc.setFontSize(11);
    contentList.forEach((item, index) => {
      doc.text(item, 105, 150 + (index * 10), { align: 'center' });
    });
    
    doc.setFontSize(10);
    doc.text(`Generated on: ${formatDateFull(new Date())}`, 105, 240, { align: 'center' });
    doc.text("RevalPro - Nursing Revalidation Assistance App", 105, 250, { align: 'center' });
    
    // --- PRACTICE HOURS ---
    doc.addPage();
    await renderPracticeHoursToDoc(doc, data);
    
    // --- CPD RECORDS ---
    doc.addPage();
    await renderCpdRecordsToDoc(doc, data);
    
    // --- FEEDBACK ---
    doc.addPage();
    await renderFeedbackToDoc(doc, data);
    
    // --- REFLECTIVE ACCOUNTS ---
    doc.addPage();
    await renderReflectiveAccountsToDoc(doc, data);
    
    // --- REFLECTIVE DISCUSSION ---
    doc.addPage();
    await renderReflectiveDiscussionToDoc(doc, data);
    
    // --- HEALTH DECLARATION ---
    doc.addPage();
    await renderHealthDeclarationToDoc(doc, data);
    
    // --- CONFIRMATION ---
    doc.addPage();
    await renderConfirmationToDoc(doc, data);
    
    // Add page numbers to all pages
    addNmcFooter(doc);
    
    // Generate and download the combined PDF
    const pdfOutput = doc.output('blob');
    const url = URL.createObjectURL(pdfOutput);
    const a = document.createElement("a");
    a.href = url;
    a.download = `nmc-revalidation-pack-${formatDateShort(new Date()).replace(/\//g, '-')}.pdf`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Update toast to confirm completion
    if (document.body.querySelector('.fixed.bottom-4.right-4')) {
      const toast = document.body.querySelector('.fixed.bottom-4.right-4') as HTMLElement;
      toast.textContent = 'NMC-compliant documents created successfully!';
      toast.className = 'fixed bottom-4 right-4 bg-green-600 text-white px-4 py-2 rounded shadow-lg z-50';
      
      // Remove toast after 3 seconds
      setTimeout(() => {
        if (toast && toast.parentNode) {
          toast.parentNode.removeChild(toast);
        }
      }, 3000);
    }
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error("Error generating PDF pack:", error);
    
    // Show error message
    if (document.body.querySelector('.fixed.bottom-4.right-4')) {
      const toast = document.body.querySelector('.fixed.bottom-4.right-4') as HTMLElement;
      toast.textContent = 'Error creating NMC documents. Please try again.';
      toast.className = 'fixed bottom-4 right-4 bg-red-600 text-white px-4 py-2 rounded shadow-lg z-50';
      
      // Remove toast after 4 seconds
      setTimeout(() => {
        if (toast && toast.parentNode) {
          toast.parentNode.removeChild(toast);
        }
      }, 4000);
    }
    
    throw new Error("Failed to generate revalidation pack");
  }
}

/**
 * Generate and download a specific form as PDF
 */
export async function downloadSpecificForm(formType: string): Promise<void> {
  try {
    let pdf: jsPDF;
    let filename: string;
    
    switch (formType) {
      case 'practiceHours':
        pdf = await generatePracticeHoursPdf();
        filename = 'practice-hours-log';
        break;
      case 'cpd':
        pdf = await generateCpdRecordsPdf();
        filename = 'cpd-records';
        break;
      case 'feedback':
        pdf = await generateFeedbackPdf();
        filename = 'feedback-log';
        break;
      case 'reflectiveAccounts':
        pdf = await generateReflectiveAccountsPdf();
        filename = 'reflective-accounts';
        break;
      case 'reflectiveDiscussion':
        pdf = await generateReflectiveDiscussionPdf();
        filename = 'reflective-discussion-form';
        break;
      case 'healthDeclaration':
        pdf = await generateHealthDeclarationPdf();
        filename = 'health-character-declaration';
        break;
      case 'confirmation':
        pdf = await generateConfirmationPdf();
        filename = 'confirmation-form';
        break;
      default:
        throw new Error(`Unknown form type: ${formType}`);
    }
    
    // Generate and download the PDF with improved browser compatibility
    const pdfOutput = pdf.output('blob');
    const url = URL.createObjectURL(pdfOutput);
    const a = document.createElement("a");
    
    // Set download attributes
    a.href = url;
    a.download = `${filename}-${formatDateShort(new Date()).replace(/\//g, '-')}.pdf`;
    a.style.display = 'none';
    
    // Add to document and trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error(`Error generating ${formType} PDF:`, error);
    throw error;
  }
}

/**
 * Generate and download raw data as JSON
 */
export async function downloadRawData(): Promise<void> {
  try {
    const blob = await generateJsonExport();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    
    a.href = url;
    a.download = `revalpro-data-export-${formatDateShort(new Date()).replace(/\//g, '-')}.json`;
    a.style.display = 'none';
    
    document.body.appendChild(a);
    a.click();
    
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error("Error downloading raw data:", error);
    throw error;
  }
}
