import { formatDateFull, formatDateShort } from "./date-utils";
import { calculatePercentage } from "./utils";
import { exportAllData } from "./storage";
import type {
  UserProfile,
  PracticeHours,
  CpdRecord,
  FeedbackRecord,
  ReflectiveAccount,
  ReflectiveDiscussion,
  HealthDeclaration,
  Confirmation
} from "@shared/schema";

/**
 * Generate a download blob for JSON export
 */
export async function generateJsonExport(): Promise<Blob> {
  const data = await exportAllData();
  return new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
}

/**
 * Helper function to create a simple PDF document with summary information
 * Note: This is a placeholder for actual PDF generation
 * A real implementation would use a PDF library like pdfmake or jspdf
 */
export async function generateSummaryPdf(): Promise<string> {
  // In a real implementation, this would use a PDF library
  // For demo purposes, we'll create a JSON string and convert it to a Blob
  const data = await exportAllData();
  
  const userProfile = data.userProfile[0] as UserProfile;
  const practiceHoursTotal = (data.practiceHours as PracticeHours[]).reduce((sum, record) => sum + record.hours, 0);
  const cpdRecords = data.cpdRecords as CpdRecord[];
  const feedbackRecords = data.feedbackRecords as FeedbackRecord[];
  const reflectiveAccounts = data.reflectiveAccounts as ReflectiveAccount[];
  const reflectiveDiscussion = data.reflectiveDiscussion[0] as ReflectiveDiscussion;
  const healthDeclaration = data.healthDeclaration[0] as HealthDeclaration;
  const confirmation = data.confirmation[0] as Confirmation;
  
  const now = new Date();
  const cpdTotal = cpdRecords.reduce((sum, record) => sum + record.hours, 0);
  const cpdParticipatory = cpdRecords
    .filter(record => record.participatory)
    .reduce((sum, record) => sum + record.hours, 0);
  
  // Calculate completion percentages
  const practiceHoursPercentage = calculatePercentage(practiceHoursTotal, 450);
  const cpdPercentage = calculatePercentage(cpdTotal, 35);
  const feedbackPercentage = calculatePercentage(feedbackRecords.length, 5);
  const reflectionPercentage = calculatePercentage(reflectiveAccounts.length, 5);
  const reflectiveDiscussionCompleted = reflectiveDiscussion?.completed ? 100 : 0;
  const healthDeclarationCompleted = healthDeclaration?.completed ? 100 : 0;
  const confirmationCompleted = confirmation?.completed ? 100 : 0;
  
  // Calculate overall percentage
  const overallPercentage = Math.round(
    (practiceHoursPercentage + cpdPercentage + feedbackPercentage + reflectionPercentage + 
     reflectiveDiscussionCompleted + healthDeclarationCompleted + confirmationCompleted) / 7
  );
  
  // Create a simple summary object
  const summary = {
    title: "NurseValidate UK - Revalidation Summary",
    generatedOn: formatDateFull(now),
    nurse: {
      name: userProfile?.name || "Not provided",
      registrationNumber: userProfile?.registrationNumber || "Not provided",
      expiryDate: userProfile?.expiryDate ? formatDateFull(userProfile.expiryDate) : "Not provided",
    },
    overallCompletion: `${overallPercentage}%`,
    requirements: [
      {
        name: "Practice Hours",
        required: "450 hours",
        completed: `${practiceHoursTotal} hours`,
        percentage: `${practiceHoursPercentage}%`,
      },
      {
        name: "CPD Hours",
        required: "35 hours (20 participatory)",
        completed: `${cpdTotal} hours (${cpdParticipatory} participatory)`,
        percentage: `${cpdPercentage}%`,
      },
      {
        name: "Feedback Records",
        required: "5 records",
        completed: `${feedbackRecords.length} records`,
        percentage: `${feedbackPercentage}%`,
      },
      {
        name: "Reflective Accounts",
        required: "5 accounts",
        completed: `${reflectiveAccounts.length} accounts`,
        percentage: `${reflectionPercentage}%`,
      },
      {
        name: "Reflective Discussion",
        required: "1 discussion",
        completed: reflectiveDiscussion?.completed ? "Completed" : "Not completed",
        percentage: `${reflectiveDiscussionCompleted}%`,
      },
      {
        name: "Health & Character Declaration",
        required: "Completed declaration",
        completed: healthDeclaration?.completed ? "Completed" : "Not completed",
        percentage: `${healthDeclarationCompleted}%`,
      },
      {
        name: "Confirmation",
        required: "Completed confirmation",
        completed: confirmation?.completed ? "Completed" : "Not completed",
        percentage: `${confirmationCompleted}%`,
      },
    ],
    disclaimer: "This is a summary generated by NurseValidate UK. It is not an official NMC document.",
  };
  
  return JSON.stringify(summary, null, 2);
}

/**
 * Generate and download a revalidation summary PDF
 */
export async function downloadRevalidationSummary(): Promise<void> {
  try {
    // For a real implementation, this would generate a PDF using a library
    // For this demo, we'll create a text file with JSON content
    const summaryData = await generateSummaryPdf();
    const blob = new Blob([summaryData], { type: "application/json" });
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `revalidation-summary-${formatDateShort(new Date()).replace(/\//g, '-')}.json`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error("Error generating PDF summary:", error);
    throw new Error("Failed to generate revalidation summary");
  }
}

/**
 * Generate and download raw data as JSON
 */
export async function downloadRawData(): Promise<void> {
  try {
    const blob = await generateJsonExport();
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `revalidation-data-${formatDateShort(new Date()).replace(/\//g, '-')}.json`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
  } catch (error) {
    console.error("Error exporting data:", error);
    throw new Error("Failed to export revalidation data");
  }
}
